/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.CardLayout;

/**
 *
 * @author ACER
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        formPanel newFormJPanel = new formPanel(jbottomPanel);
        this.jbottomPanel.add(newFormJPanel);
        CardLayout layout = (CardLayout)this.jbottomPanel.getLayout();
        layout.next(jbottomPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jtopPanel = new javax.swing.JPanel();
        jformButton = new javax.swing.JButton();
        jviewButton = new javax.swing.JButton();
        jbottomPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jformButton.setText("Form");
        jformButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jformButtonActionPerformed(evt);
            }
        });

        jviewButton.setText("View");
        jviewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jviewButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jtopPanelLayout = new javax.swing.GroupLayout(jtopPanel);
        jtopPanel.setLayout(jtopPanelLayout);
        jtopPanelLayout.setHorizontalGroup(
            jtopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtopPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jformButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(jviewButton)
                .addGap(56, 56, 56))
        );
        jtopPanelLayout.setVerticalGroup(
            jtopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtopPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jtopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jformButton)
                    .addComponent(jviewButton))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(jtopPanel);

        jbottomPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(jbottomPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jviewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jviewButtonActionPerformed
        // TODO add your handling code here:
        viewPanel newViewJPanel = new viewPanel();
        this.jbottomPanel.add(newViewJPanel);
        CardLayout layout = (CardLayout) this.jbottomPanel.getLayout();
        layout.next(jbottomPanel);
    }//GEN-LAST:event_jviewButtonActionPerformed

    private void jformButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jformButtonActionPerformed

        // TODO add your handling code here:
        formPanel newFormJPanel = new formPanel(jbottomPanel);
        this.jbottomPanel.add(newFormJPanel,"FormPanel");
        CardLayout layout = (CardLayout) this.jbottomPanel.getLayout();
        layout.show(jbottomPanel,"FormPanel");
    }//GEN-LAST:event_jformButtonActionPerformed

    private void formjButtonActionPerformed(java.awt.event.ActionEvent evt){
        formPanel newFormJPanel = new formPanel(jbottomPanel);
        this.jbottomPanel.add(newFormJPanel,"FormPanel");
        CardLayout layout = (CardLayout) this.jbottomPanel.getLayout();
        layout.show(jbottomPanel,"FormPanel");
        
    }
    
    private void viewjButtonActionPerformed(java.awt.event.ActionEvent evt){
        viewPanel newviewPanel = new viewPanel();
        this.jbottomPanel.add(newviewPanel,"ViewPanel");
        CardLayout layout = (CardLayout) this.jbottomPanel.getLayout();
        layout.show(jbottomPanel,"ViewPanel");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel jbottomPanel;
    private javax.swing.JButton jformButton;
    private javax.swing.JPanel jtopPanel;
    private javax.swing.JButton jviewButton;
    // End of variables declaration//GEN-END:variables
}
