/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ButtonModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import utility.DatabaseConnector;
import javax.swing.table.DefaultTableModel;
import model.Paitent;

/**
 *
 * @author ACER
 */
public class viewPanel extends javax.swing.JPanel {

    ImageIcon ProfilePicture;
    Paitent selectedpaitent;
    ArrayList <Paitent> paitents;
    Paitent p1;
    /**
     * Creates new form viewPanel
     */
    public viewPanel() {
        initComponents();
        populateTable();
    }
    
    public viewPanel(Paitent p1){
        this.p1=p1;
        initComponents();
        populateData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGender = new javax.swing.ButtonGroup();
        jLabelFname = new javax.swing.JLabel();
        jTextFieldfname = new javax.swing.JTextField();
        jLabellname = new javax.swing.JLabel();
        jTextFieldlname = new javax.swing.JTextField();
        jLabelGender = new javax.swing.JLabel();
        jRadioButtonmale = new javax.swing.JRadioButton();
        jRadioButtonfemale = new javax.swing.JRadioButton();
        jRadioButtonother = new javax.swing.JRadioButton();
        jLabelage = new javax.swing.JLabel();
        jTextFieldage = new javax.swing.JTextField();
        jLabelemail = new javax.swing.JLabel();
        jTextFieldmail = new javax.swing.JTextField();
        imgJLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonsubmit = new javax.swing.JButton();
        jpatientType = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientjTable = new javax.swing.JTable();
        deleteButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 102, 255));

        jLabelFname.setText("FIRST NAME:");

        jLabellname.setText("LAST NAME :");

        jTextFieldlname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldlnameActionPerformed(evt);
            }
        });

        jLabelGender.setText("GENDER :");

        jRadioButtonmale.setText("MALE");
        jRadioButtonmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonmaleActionPerformed(evt);
            }
        });

        jRadioButtonfemale.setText("FEMALE");
        jRadioButtonfemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonfemaleActionPerformed(evt);
            }
        });

        jRadioButtonother.setText("OTHER");

        jLabelage.setText("AGE:");

        jTextFieldage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldageActionPerformed(evt);
            }
        });

        jLabelemail.setText("Email:");

        jLabel1.setText("Patient Type");

        jButtonsubmit.setText("SUBMIT");
        jButtonsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsubmitActionPerformed(evt);
            }
        });

        jpatientType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Appointment", "Walk-in" }));

        patientjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "name", "gender", "last_name", "age", "email", "paitent_type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(patientjTable);

        deleteButton.setText("Delete Row");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        editButton.setText("Edit Row");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabellname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldlname, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldfname, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelGender, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelemail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelage, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonmale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonfemale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonother, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldage, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jpatientType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 17, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(deleteButton)
                                .addGap(51, 51, 51)
                                .addComponent(jButtonsubmit)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imgJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editButton)
                        .addGap(46, 46, 46)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFname)
                            .addComponent(jTextFieldfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabellname, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldlname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelGender)
                            .addComponent(jRadioButtonmale)
                            .addComponent(jRadioButtonfemale)
                            .addComponent(jRadioButtonother))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelage)
                                    .addComponent(jTextFieldage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelemail)
                                    .addComponent(jTextFieldmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel1)
                                            .addComponent(jpatientType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButtonsubmit)
                                            .addComponent(deleteButton)))
                                    .addComponent(imgJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(editButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(235, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldlnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldlnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldlnameActionPerformed

    private void jRadioButtonmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonmaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonmaleActionPerformed

    private void jRadioButtonfemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonfemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonfemaleActionPerformed

    private void jButtonsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsubmitActionPerformed
        
        Paitent newPaitent = new Paitent();
        newPaitent.setFname(this.jTextFieldfname.getText());
        newPaitent.setGender(this.buttonGroupGender.getSelection().getActionCommand());
        newPaitent.setLname(this.jTextFieldlname.getText());
        newPaitent.setAge(Integer.parseInt(jTextFieldage.getText()));
        newPaitent.setEmail(this.jTextFieldmail.getText());
        newPaitent.setPatientType(this.jpatientType.getSelectedItem().toString());
        try{
        DatabaseConnector.updatePaitent(selectedpaitent, newPaitent);
        System.out.println("The record has been changed successfully");
        populateTable();  
        }catch(Exception ex){
            System.out.println("Caught Successfully");
            System.out.println(ex);
        }
//        try{
//            String name=this.jTextFieldfname.getText();
//            String gender=this.buttonGroupGender.getSelection().getActionCommand();
//            String patientType= this.jpatientType.getSelectedItem().toString();            
//            int age= Integer.parseInt(jTextFieldage.getText());
//            String first_name= this.jTextFieldfname.getText();
//            String last_name= this.jTextFieldlname.getText();
//            //String msgtxt= this.jTextFieldTextMessage.getText();
//            String email= this.jTextFieldmail.getText();
//            String displayMessage="first name: "+first_name+" last name: "+last_name+" Email: "+email+" age: "+age;
//            System.out.println(this.jTextFieldfname.getText());
//            System.out.println(this.jTextFieldlname.getText());
//            System.out.println(this.buttonGroupGender.getSelection().getActionCommand());
//            System.out.println(this.jTextFieldmail.getText());
//            System.out.println(this.jTextFieldage.getText());
//            if(name.equals("")|| patientType.equals("")){
//                displayMessage= "Maybe you forgot to enter your name or patient Type ";
//            }else {
//                displayMessage="Name is: "+first_name+ "Last Name: "+last_name+" Gender is: "+gender+" Patient Type: "+patientType+"Age: "+age;
//            }
//
//            //JOptionPane.showMessageDialog(this, displayMessage,"Success", Height, this.ProfilePicture);
//            JOptionPane.showMessageDialog(this, displayMessage,"Success", HEIGHT, this.ProfilePicture);
//        }
//        catch (NullPointerException ne)
//        {
//            String errorMessage="You must enter things in  name and Gender";
//            JOptionPane.showMessageDialog(this, errorMessage);
//        }
//        catch (Exception e )
//        { System.out.println("xxEroorrrrrxx");
//            System.out.println(e);
//        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonsubmitActionPerformed

    private void jTextFieldageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldageActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        
        int selectedRowIndex = this.patientjTable.getSelectedRow();
         try{
         this.selectedpaitent = this.paitents.get(selectedRowIndex);
         DatabaseConnector.deletePaitent(selectedpaitent);
         System.out.println("Patient deleted Successfully");
         populateTable();
         }catch(Exception ex){
             System.out.println("Caught all Exceptions");
             System.out.println(ex);
         }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = this.patientjTable.getSelectedRow();
        this.selectedpaitent = this.paitents.get(selectedRowIndex);
        populateData();
    }//GEN-LAST:event_editButtonActionPerformed

    public void populateTable(){
        this.paitents = DatabaseConnector.getPaitents();
        DefaultTableModel model = (DefaultTableModel) this.patientjTable.getModel();
        model.setRowCount(0);
        for(Paitent p1: paitents){
            Object [] rows = new Object[7];
            rows[0] = p1.getId();
            rows[1]=p1.getFname();
            rows[2]=p1.getGender();
            rows[3]=p1.getLname();
            rows[4]=p1.getAge();
            rows[5]=p1.getEmail();
            rows[6]=p1.getPatientType();
            model.addRow(rows);
        }
    }
    
    public void populateData(){
        this.jTextFieldfname.setText(p1.getFname());
        this.jTextFieldlname.setText(p1.getLname());
        this.jTextFieldmail.setText(p1.getEmail());
        String gender = p1.getGender();
        if(gender.equals("MALE")){
            this.buttonGroupGender.setSelected(this.jRadioButtonmale.getModel(),true);
        }else if (gender.equals("FEMALE")){
            this.buttonGroupGender.setSelected(this.jRadioButtonfemale.getModel(),true);
        }else{
            this.buttonGroupGender.setSelected(this.jRadioButtonother.getModel(),true);
        }
        this.jpatientType.setSelectedItem(p1.getPatientType());
        this.imgJLabel.setIcon((Icon) p1.getProfilePicture());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupGender;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel imgJLabel;
    private javax.swing.JButton jButtonsubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFname;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelage;
    private javax.swing.JLabel jLabelemail;
    private javax.swing.JLabel jLabellname;
    private javax.swing.JRadioButton jRadioButtonfemale;
    private javax.swing.JRadioButton jRadioButtonmale;
    private javax.swing.JRadioButton jRadioButtonother;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldage;
    private javax.swing.JTextField jTextFieldfname;
    private javax.swing.JTextField jTextFieldlname;
    private javax.swing.JTextField jTextFieldmail;
    private javax.swing.JComboBox<String> jpatientType;
    private javax.swing.JTable patientjTable;
    // End of variables declaration//GEN-END:variables
}
  
